# Generated by Django 3.2.9 on 2021-11-22 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_follower_xamerz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xamerz',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.RenameField(
            model_name='xamerz',
            old_name='rate',
            new_name='ratings',
        ),
    ]
