# Generated by Django 3.2.9 on 2021-11-22 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20211122_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xamerz',
            old_name='ratings',
            new_name='rate',
        ),
    ]
