# Generated by Django 3.2.9 on 2021-11-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_rename_ratings_xamerz_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xamerz',
            name='date',
            field=models.CharField(max_length=50, verbose_name='дата'),
        ),
    ]
